//! Regenerates `docs/API.md` and `docs/schemas/`.
//!
//! Generated from the engine itself, by asking the `dim` binary, rather than
//! written by hand. Invariant I10 asks for a documented, versioned contract for
//! every command and binding; a contract maintained by hand is a contract that
//! is wrong by the second release, and an agent reading a stale one writes
//! confident code against an API that no longer exists.
//!
//! The artifacts are committed so that contributors and agents read the same
//! source of truth — a rare case where two audiences want identical files.

use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

pub fn run() -> Result<(), String> {
    let root = crate::workspace_root();
    let docs = root.join("docs");
    let schemas = docs.join("schemas");
    std::fs::create_dir_all(&schemas).map_err(|e| format!("creating docs/schemas: {e}"))?;

    let codes = dim(&root, &["api", "codes", "--json"])?;
    let kinds = dim(&root, &["api", "kinds", "--json"])?;
    let commands = dim(&root, &["api", "schema", "--json"])?;
    let tools = dim(&root, &["api", "tools", "--json"])?;
    let lua_globals = dim(&root, &["api", "globals", "--json"])?;
    let reserved = dim(&root, &["api", "reserved", "--json"])?;
    let ids = dim(&root, &["api", "ids", "--json"])?;

    write_json(&schemas.join("diagnostics.json"), &codes)?;
    write_json(&schemas.join("node-kinds.json"), &kinds)?;
    write_json(&schemas.join("commands.json"), &commands)?;
    write_json(&schemas.join("mcp-tools.json"), &tools)?;

    let markdown = render_markdown(
        &codes,
        &kinds,
        &commands,
        &tools,
        &lua_globals,
        &reserved,
        &ids,
    )?;
    let path = docs.join("API.md");
    std::fs::write(&path, markdown).map_err(|e| format!("writing {}: {e}", path.display()))?;
    eprintln!("xtask: wrote docs/API.md and docs/schemas/");
    Ok(())
}

/// Run the `dim` binary and return its JSON result.
fn dim(root: &Path, args: &[&str]) -> Result<serde_json::Value, String> {
    let output = Command::new(env!("CARGO"))
        .current_dir(root)
        .args(["run", "--quiet", "-p", "dimetric-agent", "--"])
        .args(args)
        .output()
        .map_err(|e| format!("running dim {}: {e}", args.join(" ")))?;
    if !output.status.success() {
        return Err(format!(
            "dim {} failed:\n{}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let envelope: serde_json::Value = serde_json::from_str(&text)
        .map_err(|e| format!("dim {} gave invalid JSON: {e}", args.join(" ")))?;
    Ok(envelope
        .get("result")
        .cloned()
        .unwrap_or(serde_json::Value::Null))
}

/// Squeeze runs of whitespace into single spaces.
fn collapse(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn write_json(path: &Path, value: &serde_json::Value) -> Result<(), String> {
    let text = serde_json::to_string_pretty(value)
        .map_err(|e| format!("serializing {}: {e}", path.display()))?;
    std::fs::write(path, format!("{text}\n"))
        .map_err(|e| format!("writing {}: {e}", path.display()))
}

fn render_markdown(
    codes: &serde_json::Value,
    kinds: &serde_json::Value,
    commands: &serde_json::Value,
    tools: &serde_json::Value,
    lua_globals: &serde_json::Value,
    reserved: &serde_json::Value,
    ids: &serde_json::Value,
) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(
        "# Dimetric API reference\n\n\
         Generated by `cargo xtask gen-docs`. Do not hand-edit — your changes will be\n\
         overwritten, and the point of generating it is that it cannot disagree with the\n\
         code.\n\n\
         Machine-readable versions of everything below are in `docs/schemas/`.\n\n",
    );

    // -- commands --------------------------------------------------------
    out.push_str(
        "## Commands\n\n\
         Every mutation the engine can perform. The editor, the CLI and an agent all go\n\
         through this list and nothing else (invariant I1). Commands marked undoable go on\n\
         the undo stack; the rest act on the project rather than the open scene.\n\n\
         | Command | Fields | Undoable |\n|---|---|---|\n",
    );
    let list = commands
        .get("commands")
        .and_then(|c| c.as_array())
        .ok_or("command schema has no `commands` array")?;
    for command in list {
        let name = command.get("name").and_then(|v| v.as_str()).unwrap_or("?");
        let fields = command
            .get("fields")
            .and_then(|f| f.as_array())
            .map(|f| {
                f.iter()
                    .filter_map(|v| v.as_str())
                    .map(|s| format!("`{s}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            })
            .unwrap_or_default();
        let undoable = command
            .get("undoable")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let _ = writeln!(
            out,
            "| `{name}` | {} | {} |",
            if fields.is_empty() {
                "—".into()
            } else {
                fields
            },
            if undoable { "yes" } else { "no" }
        );
    }

    // -- node kinds ------------------------------------------------------
    out.push_str(
        "\n## Node kinds\n\n\
         A node's `kind` selects the schema its properties are validated against. Unknown\n\
         properties are a hard error (`DIM0301`), so a kind must register before its\n\
         scenes will load — which is also what makes the \"did you mean\" suggestion\n\
         possible.\n\n\
         Properties equal to their default are omitted from the file and filled in on\n\
         load, so a scene does not grow every time a kind gains a property.\n",
    );

    // The keys every node carries, which the per-kind tables below do *not*
    // repeat. Generated from `dimetric_scene::schema::RESERVED_KEY_DOCS`,
    // with a test in that crate holding it against `RESERVED_KEYS`, because
    // this reference spent four milestones referring to "the reserved keys"
    // without listing them anywhere.
    out.push_str(
        "\n### Keys every node has\n\n\
         These sit on every node whatever its kind, and a kind may not declare a\n\
         property that shadows one (`DIM0104`). They are *not* repeated in the\n\
         per-kind tables below.\n\n\
         | Key | What it does |\n|---|---|\n",
    );
    for key in reserved["reserved"].as_array().into_iter().flatten() {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            key["name"].as_str().unwrap_or_default(),
            // The source strings wrap with Rust's `\` continuation, which keeps
            // the next line's indentation. Harmless in a doc comment, a run of
            // spaces in the middle of a table cell here.
            collapse(key["doc"].as_str().unwrap_or_default())
        );
    }
    out.push_str(
        "\nDraw order sorts on `layer` first, then `z`, then depth, then whatever the\n\
         batcher splits on, and finally the node id so that no two sprites are ever in\n\
         an ambiguous order. Depth is the world position under the current projection,\n\
         quantised to whole units so a sprite drifting by a fraction of a pixel cannot\n\
         flicker past its neighbour. **Nudging a sprite\'s position to force it in front\n\
         of another is never the answer** — that is what `z` and `layer` are for.\n",
    );
    let kind_list = kinds
        .get("kinds")
        .and_then(|k| k.as_array())
        .ok_or("kind schema has no `kinds` array")?;
    for kind in kind_list {
        let name = kind.get("kind").and_then(|v| v.as_str()).unwrap_or("?");
        let doc = kind.get("doc").and_then(|v| v.as_str()).unwrap_or("");
        let _ = write!(out, "\n### `{name}`\n\n{doc}\n\n");
        let properties = kind
            .get("properties")
            .and_then(|p| p.as_array())
            .cloned()
            .unwrap_or_default();
        if properties.is_empty() {
            out.push_str("No properties beyond the reserved keys.\n");
            continue;
        }
        out.push_str("| Property | Type | Default | Notes |\n|---|---|---|---|\n");
        for property in properties {
            let field = |key: &str| {
                property
                    .get(key)
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string()
            };
            let required = property
                .get("required")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let default = property
                .get("default")
                .and_then(|v| v.as_str())
                .map(|d| format!("`{d}`"))
                .unwrap_or_else(|| {
                    if required {
                        "**required**".into()
                    } else {
                        "—".into()
                    }
                });
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {default} | {} |",
                field("name"),
                field("type"),
                field("doc").replace('|', "\\|")
            );
        }
    }

    // -- diagnostics -----------------------------------------------------
    out.push_str(
        "\n## Diagnostic codes\n\n\
         Every failure carries one of these, plus a source location and a\n\
         machine-readable payload (invariant I9). Match on the code; never parse the\n\
         message. Codes are never reused for a different meaning.\n\n\
         | Code | Severity | Meaning |\n|---|---|---|\n",
    );
    let code_list = codes
        .get("codes")
        .and_then(|c| c.as_array())
        .ok_or("diagnostics have no `codes` array")?;
    for code in code_list {
        let field = |key: &str| code.get(key).and_then(|v| v.as_str()).unwrap_or("");
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            field("code"),
            field("severity"),
            field("summary")
        );
    }

    // -- mcp tools -------------------------------------------------------
    out.push_str(
        "\n## MCP tools\n\n\
         `dim mcp` serves the CLI over the Model Context Protocol. The tools are read\n\
         from the CLI itself, so this list is what the binary answers `tools/list` with.\n\
         `project`, `scene`, `json` and `id_seed` are global and omitted from the\n\
         arguments column.\n\n\
         | Tool | Arguments | What it does |\n|---|---|---|\n",
    );
    let globals = ["project", "scene", "json", "id_seed"];
    let list = tools
        .get("tools")
        .and_then(|t| t.as_array())
        .ok_or("api tools gave no list")?;
    for tool in list {
        let name = tool
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let about = tool
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let schema = &tool["inputSchema"];
        let required: Vec<&str> = schema
            .get("required")
            .and_then(|r| r.as_array())
            .map(|r| r.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        let mut arguments: Vec<String> = schema
            .get("properties")
            .and_then(|p| p.as_object())
            .map(|p| p.keys().cloned().collect())
            .unwrap_or_default();
        arguments.retain(|a| !globals.contains(&a.as_str()));
        arguments.sort();
        let rendered: Vec<String> = arguments
            .iter()
            .map(|a| {
                if required.contains(&a.as_str()) {
                    format!("`{a}`*")
                } else {
                    format!("`{a}`")
                }
            })
            .collect();
        let _ = writeln!(
            out,
            "| `{name}` | {} | {about} |",
            if rendered.is_empty() {
                "—".to_string()
            } else {
                rendered.join(", ")
            }
        );
    }
    out.push_str("\nAn argument marked `*` is required.\n");

    // Generated from the manifest in `dimetric_sim::api_doc`, not typed here.
    // This section used to be a literal, and it drifted: M12 added the whole
    // `ui` global and the reference went on listing ten of eleven. A test in
    // `dimetric-sim` compares that manifest against a real sandbox, so the
    // table below cannot claim an API that does not exist, or miss one that
    // does.
    out.push_str("\n## Lua API\n\nScripts see exactly these globals and nothing else.\n\n");
    out.push_str("| Global | What it gives you |\n|---|---|\n");
    for global in lua_globals["globals"].as_array().into_iter().flatten() {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            global["name"].as_str().unwrap_or_default(),
            global["about"].as_str().unwrap_or_default()
        );
    }
    out.push_str(
        "\nPlus the parts of the Lua standard library the sandbox re-exports: \
         `assert`, `error`, `ipairs`, `next`, `pairs`, `pcall`, `select`, `tonumber`, \
         `tostring`, `type`, `xpcall`, `rawequal`, `rawget`, `rawlen`, `setmetatable`, \
         `getmetatable`, `string`, `table`, and a reduced `math` holding only the \
         exactly-defined integer operations. `rawset` is deliberately absent: it writes \
         past the `__newindex` that keeps a required module read-only.\n\n",
    );
    out.push_str(
        "A node handle supports `get`, `set`, `find`, `parent`, `children`, `emit`,\n\
         `destroy`, `set_velocity`, `velocity`, `world_pos`, `has_tag`, `name`, `path`,\n\
         `kind`, `valid`, and — on a `Sound` node — `play` and `stop`. Indexing a handle\n\
         reads and writes script variables, except for `pos`, `rot` and `visible`, which\n\
         reach the node's transform.\n\n\
         `self.thing = nil` clears a script variable, as it clears a key from any\n\
         other Lua table, and `self.thing` then reads back as `nil`. Nil is not a value\n\
         the engine stores, so anywhere else — `node:set`, `profile.put`, a tween\n\
         target — it is refused rather than turned into something else.\n\n\
         ### Reading a property and writing it back\n\n\
         `node:get` and `node:set` address the *kind properties* — the ones a kind's\n\
         schema declares. The keys every node has are not among them: they live on the\n\
         node itself, so `node:set(\"visible\", false)` would shadow the real one rather\n\
         than change it, and is refused with `DIM0104`. Write `self.visible = false`,\n\
         which reaches the node.\n\n\
         A write may not change a property's type (`DIM0505`). The authored value is\n\
         the type of record, because it came through the parser, which had the schema.\n\n\
         When the node carries no value for the key, the **kind's declared type** is\n\
         the record instead. That is not the same as nothing being checked. Canonical\n\
         form omits a property equal to its default and the loader fills those back\n\
         in, so the keys absent from a node are the ones with **no default and not\n\
         required** — `region` on a sprite, `limits` on a camera, `cone_angle` on a\n\
         light, `tile_size` on a tile layer, and any such property of a kind the\n\
         project declares. A write to one of those is reshaped to the declared type,\n\
         or refused with the same `DIM0505`. It is what keeps\n\
         `node:set(\"region\", { 0, 0, 24, 3 })` from storing a list of integers on a\n\
         sprite that never authored a region — which drew correctly, and then did not\n\
         survive a save.\n\n\
         Two things only the schema knows are checked along with the type: an enum takes\n\
         only its own variants, and a reference property only its own prefix — a\n\
         `scene:` reference written into an `asset:` property is refused rather than\n\
         stored, because stored it would be a save that will not open.\n\n\
         A key the kind does not declare at all is refused with `DIM0301`, the same code\n\
         the loader raises for it. There is nowhere for such a property to go: a save\n\
         would carry it out and then fail to load back in, so the spelling is worth\n\
         reporting at the line that wrote it.\n\n\
         Four types reach a script as a string, because a string is how they are\n\
         written: a colour is `#rrggbbaa`, an angle is degrees, a reference is\n\
         `asset:sprites/bogling`, an enum is its variant. A rect reaches it as a table,\n\
         `{ pos = vec2, size = vec2 }`. Writing any of those back is *not* a type change\n\
         — what arrives is re-read by the same parser the scene format uses, so\n\
         `node:set(k, node:get(k))` round-trips on every type, and something that does\n\
         not parse is refused with the reason rather than stored.\n\n\
         A rect also takes the form the engine writes everywhere else, so a script\n\
         building one out of numbers need not make two vectors:\n\n\
         ```lua\n\
         node:set(\"region\", \"[0, 0, 8, 4]\")   -- or { 0, 0, 8, 4 }\n\
         ```\n\n\
         ### Colours\n\n\
         ```lua\n\
         bar:set(\"modulate\", color.rgba(255, 143, 74, 255))\n\
         bar:set(\"modulate\", color.rgb(255, 143, 74))   -- opaque, said aloud\n\
         bar:set(\"modulate\", \"#ff8f4aff\")              -- what `get` hands back\n\
         ```\n\n\
         Channels are bytes and are refused outside `0..255` rather than clamped: a\n\
         clamp makes a colour the author did not write and does not mention the\n\
         arithmetic that produced it. Alpha is explicit, here as in a `.dim` file —\n\
         `#ff8f4a` is not a colour in this engine, and `color.rgb` is how to mean\n\
         opaque. A colour is a node property, so it is hashed and replays like `pos`.\n\n\
         ### Scale\n\n\
         `scale` is one of the keys every node has, and it is drawn: a `Sprite2D` or an\n\
         `AnimatedSprite2D` multiplies its quad by its **world** scale, so scaling a\n\
         parent scales its children. A negative component mirrors the quad, which makes\n\
         `flip_h` sugar for `scale = [-1, 1]` — and doing both cancels out, because they\n\
         are two ways to say the same thing.\n\n\
         `scale` can be tweened like any other vector, which is what a health bar that\n\
         shrinks and a sprite that squashes on a hit are made of.\n\n\
         A `TileLayer` and a `Label` are deliberately **not** scaled by it. A tile\n\
         layer\'s sprite size and the step between its cells are different numbers, and\n\
         scaling one without the other breaks the lattice; a label\'s glyph advance is in\n\
         screen pixels, so scaling it would grow the letters without spreading them.\n\
         Both want an answer of their own rather than this one.\n\n\
         ### Depth, and sorting at the feet\n\n\
         Within a layer, what draws on top is decided by depth: `y` under `TopDown`\n\
         and `x + y` under `Isometric`. A `TileLayer`'s tiles and the sprites beside\n\
         them go through the same key, which is what lets a wall tile hide a figure\n\
         standing behind it and a figure cover the wall it stands in front of.\n\n\
         The catch is that a figure is usually taller than its cell. A 28-pixel sprite\n\
         on a 16-pixel grid has to be drawn **lifted** for its feet to land on the\n\
         floor, and `offset` fed the depth as well — so lifting it six units sorted it\n\
         six units *behind* its own floor tile, which then drew over its feet. The two\n\
         ways around it were both a way of lying to the sorter: pad every sheet with\n\
         transparent rows until the centre falls at the feet, encoding a sort point in\n\
         every frame rectangle, or put the figures on a layer above all tiles, which\n\
         fixes the walls in front and breaks the walls behind.\n\n\
         `sort_offset` separates the two points:\n\n\
         ```toml\n\
         [[node]]\n\
         kind = \"AnimatedSprite2D\"\n\
         name = \"Figure\"\n\
         frames = \"asset:sprites/walk\"\n\
         offset = [0.0, -6.0]       # drawn lifted, feet on the cell\n\
         sort_offset = [0.0, 7.0]   # sorted at the feet, a nudge past the cell\n\
         ```\n\n\
         It is added to the depth position and to nothing else, in world units, so it\n\
         carries through the isometric shear rather than being a screen-space fudge.\n\
         The extra unit past the cell centre is worth having: landing exactly on the\n\
         centre ties with the figure's own floor tile and leaves the node-id tie-break\n\
         to decide, and a game should not have to depend on a tie.\n\n\
         `AnimatedSprite2D` also declares `offset` now. The renderer had always read it\n\
         for both sprite kinds and only `Sprite2D` declared it, so authoring it on the\n\
         one kind a game animates was a hard `DIM0301` — on exactly the node that needs\n\
         lifting.\n\n\
         ### Light\n\n\
         A `Light2D` is drawn into an accumulation buffer and the composite multiplies\n\
         the world by it. That multiply only happens when the **ambient** is darker\n\
         than opaque white, and until now nothing a game shipped could set it: the\n\
         agent's `--ambient` could, a project could not, a scene could not, and a\n\
         script could not. So in `dim-play` the ambient was always white and every\n\
         light a game placed added nothing at all.\n\n\
         There are two doors, and the nearer one wins:\n\n\
         ```toml\n\
         # project.toml — the floor under every scene\n\
         [render]\n\
         ambient = \"#303040ff\"\n\
         ```\n\n\
         ```toml\n\
         # a scene — this region's own light\n\
         [[node]]\n\
         kind = \"Camera2D\"\n\
         name = \"View\"\n\
         current = true\n\
         ambient = \"#604020ff\"\n\
         ```\n\n\
         A region's light is a fact about the region — a drowned march at dusk, a\n\
         foundry lit by its slag, a tomb by candles — so the current camera's `ambient`\n\
         wins over the project's, and a scene swap brings the new one with it. The\n\
         camera's property has **no default** on purpose: a camera that answered\n\
         \"white\" when it had been asked nothing would mean every scene overrode the\n\
         project's setting with the engine's, and `[render] ambient` could never apply\n\
         to any scene that has a camera — which is all of them.\n\n\
         `dim frame capture --ambient` sets the project-wide value, so a scene that\n\
         declares its own is photographed under *its* light and the flag says so\n\
         (`DIM0904`). That is deliberate: a capture is meant to be evidence about what\n\
         a player sees. Every capture now reports the ambient it drew under.\n\n\
         A dim scene with **no lights in it** dims. It used to not: the composite only\n\
         applied the ambient when the frame also carried at least one light, so a\n\
         region at dusk with no torches was drawn as if it were noon.\n\n\
         #### Keeping what a player reads out of the light\n\n\
         The multiply covers the whole world, which is right for the floor, the walls\n\
         and the figures and wrong for everything a player *reads*: a health bar over a\n\
         monster's head, a damage number, the cursor, the cells an ability can reach, a\n\
         spell effect that ought to glow rather than dim. Those are world drawing —\n\
         they sit on the board and move with the camera — so they cannot be UI controls\n\
         without re-projecting every one of them into screen space each frame, and the\n\
         UI pass is the only thing the light already skips.\n\n\
         `lit = false` on a `Sprite2D`, an `AnimatedSprite2D`, a `Label` or a\n\
         `TileLayer` leaves that drawing at full colour however dark the room gets.\n\
         Absent and `true` both dim.\n\n\
         An unlit node still **sorts and batches with everything else**; only the\n\
         multiply skips it. That matters for an overlay that belongs *under* the\n\
         figures — a layer of reachable cells between the floor and the actors — and it\n\
         is why the exemption is a mask written in draw order rather than a second\n\
         picture laid over the first: a lit figure drawn in front of an unlit marker\n\
         clears the exemption behind it, so the figure still dims.\n\n\
         ### Actions a project declares of its own\n\n\
         The engine has nine actions — `up`, `down`, `left`, `right`, `fire`,\n\
         `alt`, `dash`, `use`, `pause` — and a game may want more. An undo for a\n\
         move made this turn is a verb, not a button on a screen: it should be a\n\
         key and a pad button like any other.\n\n\
         ```toml\n\
         [input]\n\
         actions = [\"undo\", \"screens\"]   # the verbs this project has of its own\n\
         fire = [\"Space\", \"PadSouth\"]\n\
         undo = [\"KeyZ\", \"Backspace\", \"PadLB\"]\n\
         screens = [\"Tab\"]\n\
         ```\n\n\
         A declared action is read in Lua like a built-in: `input.pressed(\"undo\")`,\n\
         `held`, `released`. It is an **array** rather than a table because the\n\
         order matters: each declared action takes a bit in the recorded button\n\
         field by its position, and a recording stores raw bits.\n\n\
         So **appending is safe** and reordering is not. Append one and every log\n\
         already recorded still reads correctly, because every action keeps its bit\n\
         and the new one is simply zero — which is what not-held means. Reorder or\n\
         remove one and bit 5 names a different verb, so a recording carries the\n\
         list it was made against and a replay **refuses** a log whose list is not a\n\
         prefix of the project's (`DIM0703`). A log from before any declaration\n\
         carries none and replays against anything.\n\n\
         Declaring has to be explicit: an action name nothing recognises is still an\n\
         error, because `fier = [\"Space\"]` silently becoming a new verb nothing\n\
         reads is the typo that diagnostic exists to catch. Sixteen is the cap,\n\
         declaring a name the engine already owns is refused rather than allowed to\n\
         shadow it, and both are `DIM0903`.\n\n\
         ### Keys, pad buttons, and changing them while the game runs\n\n\
         Keys and pad buttons are **one table**. A pad used to be a constant the\n\
         engine kept to itself — `PadSouth` *was* `fire` — so a player who wanted\n\
         confirm and cancel the other way round, which is the other half of the\n\
         world's convention, had no way to say so. Now a button is a name a binding\n\
         takes like any key: `PadSouth`, `PadEast`, `PadNorth`, `PadWest`, `PadLB`,\n\
         `PadRB`, `PadLT`, `PadRT`, `PadSelect`, `PadStart`, `PadMode`,\n\
         `PadLeftThumb`, `PadRightThumb`, `PadUp`, `PadDown`, `PadLeft`,\n\
         `PadRight`.\n\n\
         A project's `[input]` replaces the defaults, so there are four cases and\n\
         each says what it means: no `[input]` gives the engine's keys **and** pad;\n\
         an `[input]` with nothing under it binds nothing, deliberately; one with\n\
         keys and no pad button gives those keys and keeps the engine's pad, so a\n\
         controller does not vanish from a project that has not written a pad layout\n\
         yet; and one naming any pad button owns all of it.\n\n\
         A Controls page changes them while the game runs, through an event:\n\n\
         ```lua\n\
         event.emit(\"input.bind\", { action = \"fire\", keys = { \"Space\", \"Enter\" } })\n\
         ```\n\n\
         The runtime applies it at the tick boundary. It replaces the action's whole\n\
         set rather than adding to it, because a Controls page knows the list and a\n\
         page that showed two keys and meant three would be lying; an empty list\n\
         unbinds. A key assigned is **taken** from whatever else held it, which is\n\
         what a player expects, and a project binding one key to two actions is a\n\
         warning rather than a silent first-wins.\n\n\
         **None of this reaches the simulation.** A recording stores actions, so a\n\
         session played under any bindings replays identically under any other —\n\
         which is exactly why remapping cannot be done in script. A script reading\n\
         `fire` and deciding it meant `alt` would put the player's preference into\n\
         the simulation's *reading* of the input, and the same recording would\n\
         replay differently under another profile. Bindings belong to the host,\n\
         before the input frame is built. A game emits its saved bindings on launch\n\
         and on every change, and keeps them in its profile.\n\n\
         ### What day it is, and what is in somebody's hands\n\n\
         A tick has no clock and no devices: the only time inside one is the tick\n\
         count (I5), and whatever a key or a pad did became a button bit long before\n\
         a script saw it. Both of those are right, and both leave a game unable to\n\
         do something reasonable — offer a daily run, or show the prompt that matches\n\
         the hand on the device.\n\n\
         ```lua\n\
         app.today()      -- \"2026-10-10\", UTC, fixed for the whole session\n\
         input.device()   -- \"keyboard\", \"mouse\" or \"pad\", whichever last moved\n\
         ```\n\n\
         Both are **in the recording**, which is what makes them safe. A title screen\n\
         offering today's descent writes the date into a label and picks a seed from\n\
         it; a prompt reading \"Space\" or showing a pad glyph is text in a `Label`.\n\
         Both of those are hashed, so a replay told today's date, or told nothing\n\
         about the pad, would diverge. The date is a line in the log's header and the\n\
         device is a column in its frames, so a replay is told exactly what the\n\
         recording was told — and a recording of a title screen still replays next\n\
         week.\n\n\
         A run nobody tells gets `2000-01-01` rather than today, because a headless\n\
         run is usually a fixture and a fixture whose output moved with the calendar\n\
         could not be checked twice. `dim run --date` and `dim-play --date` name one;\n\
         an input log's own date wins over both, since a replay has to be told what\n\
         the recording was told. UTC, not local time: two players on one calendar day\n\
         have to be offered one seed, and \"one day\" has to mean the same span\n\
         everywhere.\n\n\
         For the daily seed itself, `rng.seed(stream, n)` is the one to use rather\n\
         than `rng.reset`: a date-derived seed should not depend on the build's boot\n\
         seed.\n\n\
         ### Starting a stream over\n\n\
         Every random value comes from a named stream, created from the run seed the\n\
         first time it is asked for and kept for the rest of the session. That is\n\
         right for a run that draws once from each and wrong for a game that plays\n\
         the same run twice in one launch — a run named by a code draws from\n\
         `floor#KQPRMX` instead of `floor`, so the first play is exactly its run and\n\
         the second continues where the first left off while the screen says they are\n\
         the same.\n\n\
         ```lua\n\
         rng.reset(\"floor#KQPRMX\")      -- again from the run seed and the name\n\
         rng.seed(\"floor#KQPRMX\", code) -- again from a seed of your own\n\
         ```\n\n\
         `reset` reconstructs the stream exactly as if it had never been drawn from —\n\
         not by rewinding, because there is no record of how many draws to undo and\n\
         there should not be. `seed` is the same with a seed the game chose, which is\n\
         what makes a code portable **between** launches: `reset` goes back to the\n\
         *session* seed, so the same code in two launches is the same run only if the\n\
         session seed is, where an explicit seed does not depend on it at all. The\n\
         seed is a 64-bit pattern with nothing reserved, zero included; Lua integers\n\
         are signed, so `-1` and `0xFFFFFFFFFFFFFFFF` name one stream.\n\n\
         A reset is a **change to simulation state and is hashed**, like a draw. That\n\
         is what makes it replayable rather than a back door around the log: a reset\n\
         the hash could not see would let a replay diverge from the run it recorded\n\
         with nothing to notice. It survives a snapshot and a rollback for the same\n\
         reason — the stream's whole state is in the snapshot.\n\n\
         Resetting one stream leaves every other where it was, which is what naming\n\
         streams is for.\n\n\
         ### Hidden means hidden, for the pointer too\n\n\
         `visible` is a node's own flag and a parent's is never stored on its\n\
         children, so \"can this be seen\" is a question about the whole chain. The\n\
         renderer walked that chain; `ui::hit` read a control's own flag and nothing\n\
         else. A game that closed a screen by hiding the screen therefore got rows\n\
         that were invisible and still on top: a click in the middle of the board\n\
         landed on a row nobody could see, `ui.hovered` named it, and the board\n\
         ignored the click.\n\n\
         `Scene::is_visible` is now the one place that chain is walked, and the\n\
         renderer, the hit test and the focus order all ask it, so they cannot drift\n\
         apart again. Concretely:\n\n\
         * a control inside a hidden ancestor never wins a hit test, so `ui.hovered`,\n\
           `ui.pressed` and `ui.clicked` stop naming it;\n\
         * `ui.focus_next` skips it, and focus is **dropped** if the control holding\n\
           it becomes hidden — otherwise the keyboard stays inside a closed panel;\n\
         * `ui.focus(node)` refuses a control nothing can see and returns `false`.\n\
           Showing it and focusing it in the same tick works, because the scene is\n\
           already updated by then. Clearing focus with `ui.focus(nil)` is always\n\
           allowed.\n\n\
         Nothing is latched: a child's own `visible` is never touched, so reopening\n\
         the panel brings everything inside it back.\n\n\
         This **can** move a state hash, in exactly one case: a run whose pointer was\n\
         over a control inside a hidden ancestor used to record that control as\n\
         hovered, and now records whatever is really under the pointer. `ui.hovered`\n\
         is simulation state, so that difference is hashed. A recorded run that never\n\
         pointed at a hidden control is unaffected, which is every fixture in this\n\
         repository.\n\n\
         ### Spawning\n\n\
         `scene.spawn` returns the id the node *will* have and creates nothing yet.\n\
         A node inserted mid-tick would be going into a tree another script may be\n\
         walking, so spawns are applied at the end of the tick and the node gets\n\
         `on_ready` on the next one. The id is derived from a counter in the state\n\
         rather than drawn from the RNG, which is what makes it the same on every\n\
         machine and the same again after a rollback — and means spawning one fewer\n\
         projectile does not shift every gameplay roll after it.\n\n\
         `scene.near` and `scene.nearest` read the broadphase as it stood at the\n\
         *start* of the tick, so every script sees the same world and what one finds\n\
         does not depend on whether another has run yet.\n\n\
         ### Identifiers\n\n",
    );

    // Generated from `dimetric_core::id`, because anybody hand-writing or
    // generating a `.meta` has to know this and the only way to find it out
    // used to be reading `core/src/id.rs`. A generator that did not emitted
    // `sprites_ashfen_bogling`, and 84 sidecars were overwritten rather than
    // refused.
    let length = ids["length"].as_u64().unwrap_or_default();
    let _ = writeln!(
        out,
        "Every id is a prefix followed by exactly {length} characters.\n"
    );
    out.push_str("| Prefix | Identifies |\n|---|---|\n");
    for prefix in ids["prefixes"].as_array().into_iter().flatten() {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            prefix["prefix"].as_str().unwrap_or_default(),
            prefix["identifies"].as_str().unwrap_or_default()
        );
    }
    let _ = writeln!(
        out,
        "\nGenerated ids draw from `{}` — Crockford-style base32 with the characters \
         that are easy to misread removed. Parsing is more permissive and accepts any \
         of `[0-9a-z_]`, so a hand-written id may use an underscore; it may not be a \
         different length, and it may not omit the prefix.\n",
        ids["alphabet"].as_str().unwrap_or_default()
    );

    out.push_str(
        "\n### The `.meta` sidecar\n\n\
         An asset\'s settings live in a `<file>.meta` beside it, carrying its `id` and\n\
         how to import it. What happens to one the engine cannot use depends entirely\n\
         on whether it is **absent** or **malformed**, and the two are deliberately\n\
         different:\n\n\
         * **Absent** means no opinion. One is generated, with a derived id, and\n\
           written beside the source. Dropping a PNG into `assets/` and getting a\n\
           working sidecar is the intended way to add art.\n\
         * **Malformed** means an opinion that did not survive parsing. That asset\'s\n\
           import fails with `DIM0602` naming the file and the reason, and **the file\n\
           is left exactly as it is**. Fix it, or delete it to have one generated.\n\n\
         The second case used to invent a default and write it over the file, which\n\
         silently destroyed whatever it said — so a mistyped `id` took every\n\
         `[[clip]]` declaration in the sidecar with it.\n\n\
         ### Naming clips over a plain strip\n\n\
         An Aseprite document carries tags and those become clips. A PNG carries\n\
         nothing, so a `.meta` can name ranges over one:\n\n\
         ```toml\n\
         frames = 70\n\
         frame_ms = 120\n\n\
         [[clip]]\n\
         name = \"idle_ne\"\n\
         from = 0\n\
         to = 3\n\n\
         [[clip]]\n\
         name = \"attack_ne\"\n\
         from = 4\n\
         to = 9\n\
         looping = false\n\
         frame_ms = 60\n\
         ```\n\n\
         This is the sidecar doing what it already does: saying the things the file\n\
         itself does not. It could say a PNG is a strip of 70 frames and not that\n\
         frames 0 to 3 are an idle, and both are equally absent from the image — so\n\
         generated placeholder art, procedural sheets and anything a script assembles\n\
         could not reach `anim.play`.\n\n\
         Ranges are inclusive and absolute frame numbers, so an off-by-one is a\n\
         diagnostic naming the clip (`DIM0604`) rather than a silent shift. A range\n\
         past the end, a backwards range, a missing name and two clips sharing a name\n\
         are all refused. Declaring no clips keeps the old behaviour: one clip called\n\
         `default` over every frame.\n\n\
         Overlapping clips **warn** (`DIM0605`) rather than failing. Reusing frames is\n\
         a real technique and Aseprite tags may overlap too, so refusing would be\n\
         stricter than the tool this mirrors — but `0..3` then `3..7` when `4` was\n\
         meant is worth saying out loud.\n\n\
         ### Animating a tile\n\n\
         A tileset is a sheet of slices and a map cell holds one id that picks one of\n\
         them. That is enough for a wall and not enough for water: water, a torch and\n\
         a portal are **one tile** to the map and several slices to the eye. So the\n\
         sidecar can say which ids move, which is the same job it already does for a\n\
         strip — nothing in the PNG says that slices 5, 33, 61 and 89 are one animated\n\
         tile:\n\n\
         ```toml\n\
         [[tile]]\n\
         id = 5\n\
         frames = [5, 33, 61, 89]\n\
         frame_ms = 240\n\
         ```\n\n\
         `id` is the tile id a map stores, as painted, and `frames` are tile ids too —\n\
         the same numbers an author counts in a tileset window, not offsets into the\n\
         sheet. Putting the painted id first means a still fallback and the first frame\n\
         agree. A frame may repeat, so `[3, 4, 3, 2]` is a ripple that goes out and\n\
         comes back. `frame_ms` overrides the sheet's own, and is spelt the same as in\n\
         `[[clip]]` because it is the same quantity in the same file.\n\n\
         Tile id `0` is the empty cell, so it is not a tile and cannot be animated. A\n\
         block with no `id`, no `frames`, an empty cycle, a frame of `0`, or a second\n\
         block for the same id is refused outright (`DIM0602`, naming the file) rather\n\
         than quietly falling back to a still — a floor that does not move looks\n\
         exactly like art nobody has finished yet.\n\n\
         #### Why it is not in the scene\n\n\
         The obvious implementation is to step the map: advance every animated cell to\n\
         its next id each tick, and let the existing draw path do the rest. It is also\n\
         the wrong one, twice over. A rollback would have to undo a ripple, every\n\
         snapshot would carry a decoration, and the state hash of a replay would then\n\
         depend on the **art** — change a `.meta`, and a recorded run that verified\n\
         yesterday diverges today.\n\n\
         So the cycle is declared on the sheet, converted to whole ticks at import\n\
         against the project's tick rate, and *asked* at draw time. Which slice to draw\n\
         is a pure function of a tile id and a tick: the chunk still holds the id an\n\
         author painted, nothing writes anything down, and `dim frame capture --tick N`\n\
         gets the same answer on every machine because the tick is the same integer.\n\n\
         **Whole ticks, never the interpolation alpha.** A frame drawn midway between\n\
         two ticks shows the earlier tick's slice. That is invisible at any frame rate\n\
         worth having, and it is what keeps a golden reproducible: a cycle that\n\
         advanced on the host's accumulator remainder would be a capture that depended\n\
         on how busy the machine was.\n\n\
         ### Quitting, and the pause key\n\n\
         `app.quit()` asks whatever is running the game to stop. It is read **between\n\
         ticks**, like a scene load: the tick finishes over the state it started with and\n\
         the host acts afterwards (I8). It is not simulation state and is never hashed —\n\
         a run in which somebody chose Quit has to hash the same as one where they closed\n\
         the window, or a recorded session would replay differently depending on how it\n\
         ended, and a rollback must not un-ask. A headless run and a replay ignore it:\n\
         there is nothing for them to quit, and honouring it would let a script cut a\n\
         recorded run short.\n\n\
         `pause` is an action like any other, so `input.pressed(\"pause\")` is how a game\n\
         opens a menu of its own. The windowed runtime\'s *own* freeze is on the\n\
         keyboard\'s Pause/Break key, which is deliberately not bindable: freezing the\n\
         simulation is a debugging affordance of whatever is running the game, and a\n\
         frozen simulation cannot tick the menu that would unfreeze it.\n\n\
         ### Suspending a run, and continuing it\n\n\
         One run can be set aside and picked up later, which is the Continue row every\n\
         roguelike has. Four calls, all read **between ticks** for the same reason\n\
         `app.quit()` is:\n\n\
         | Call | What it does |\n\
         |---|---|\n\
         | `app.suspend()` | Writes the run out and stops. Carries the quit with it |\n\
         | `app.suspended()` | Whether a run this build can continue is waiting |\n\
         | `app.resume()` | Replaces the run with the suspended one, and consumes it |\n\
         | `app.discard_suspended()` | Throws it away, for a player starting a new run |\n\n\
         ```lua\n\
         function on_ready(self)\n\
         \x20 -- A Continue row, only when there is something to continue.\n\
         \x20 scene.find(\"/Menu/Continue\").visible = app.suspended()\n\
         end\n\n\
         function on_tick(self)\n\
         \x20 if ui.clicked(scene.find(\"/Menu/Continue\")) then app.resume() end\n\
         \x20 if ui.clicked(scene.find(\"/Menu/Quit\")) then app.suspend() end\n\
         \x20 if ui.clicked(scene.find(\"/Menu/Start\")) then app.discard_suspended() end\n\
         end\n\
         ```\n\n\
         **One run, consumed once.** Suspending writes it, resuming takes it. There is no\n\
         version left for a player to fall back to after playing on and losing, and\n\
         `app.suspend()` quits rather than letting a run continue past its own save —\n\
         which is why it is one call and not two.\n\n\
         **Where it lives.** A directory beside the game's `profile.toml`, holding the\n\
         canonical `scene.dim` and the `state.toml` `dim state save` writes. Text, and\n\
         readable, for the reason every other file in this engine is. Never inside a\n\
         single-file build: there is nowhere in an executable to put one.\n\n\
         **A stale save reads as no save.** One written by a different engine or format\n\
         version is refused — a save does not survive a rules change — and\n\
         `app.suspended()` then answers false, so a game never offers a Continue that\n\
         fails when pressed. The reason is reported as `DIM1002` at startup.\n\n\
         **A replay and a headless run do none of it.** Both drop the requests and answer\n\
         `app.suspended()` false, because a recorded run that depended on a file beside\n\
         it would reproduce only on the machine that made one — and a run that was\n\
         suspended must hash identically to one whose window was closed. A script that\n\
         asks anyway is told so, as `DIM1003`.\n\n\
         **What does not come back: anything a script left in Lua.** `on_ready` does not\n\
         fire again — the nodes are already readied, and re-firing it would re-run a\n\
         run's initialisation — so a handle cached in a file-scope local is nil after a\n\
         resume and the next use of it raises. Keep it in `self`, or look it up in the\n\
         hook that needs it. `dim script check` names the pattern as `DIM0508`, and the\n\
         same hazard already applies to a hot reload and to a rollback.\n\n\
         **Recording across a resume.** A session recorded with `--record` that continued\n\
         a suspended run writes a log that says so: a `resumed` line naming the state\n\
         hash the save restores to, and a `from_tick` line, so its tick numbers are the\n\
         run's. The frames before the resume are dropped, because they belong to a\n\
         different state lineage. The save is kept beside the log as `<log>.save`, since\n\
         the slot it came out of is emptied by the resume, and `dim replay` looks there\n\
         when a log says it resumed. Such a log is **refused** rather than replayed\n\
         without that save, or against a save whose hash does not match.\n\n\
         ### Telling the host something\n\n\
         `event.emit(kind, payload)` appends to a list the runtime drains with\n\
         `Session::drain_events`. That is how a Steam achievement fires, how a volume\n\
         change reaches the mixer, and how anything else platform-facing gets out: the\n\
         sandbox has no `package`, no FFI and no `io`, so the simulation cannot call a\n\
         platform SDK and should not be able to.\n\n\
         **Never hashed, and structurally so** — there is no field on `SimState` for a\n\
         later change to start hashing, the way the log lines are kept out entirely. If\n\
         emitting consumed a random number or wrote hashed state, a build with Steam\n\
         disabled would diverge from one with it on, which is the same argument that\n\
         shaped the sound list.\n\n\
         **A rollback re-emits.** Events are not snapshotted, so restoring a snapshot\n\
         does not put drained ones back and re-running a tick emits again. The\n\
         alternative would let a restore resurrect events the host had already acted\n\
         on. A host that needs exactly-once deduplicates; Steam already does, and so\n\
         can a game.\n\n\
         It is one-way. The host does not talk back: a settings menu owns its values in\n\
         the profile and emits changes outward, so the game stays the source of truth\n\
         and the runtime follows.\n\n\
         Each event carries the tick it was emitted on, so a host draining after several\n\
         ticks can still tell them apart. The payload is the `Value` scripts already\n\
         store, so lists stay ordered and there is no second serialisation. `dim run`\n\
         reports them, so an achievement that fires in a windowed build and not in CI is\n\
         visible rather than mysterious.\n\n\
         #### The kinds the engine itself owns\n\n\
         Most kinds are the game's, and the engine leaves them alone — the channel is\n\
         free text so a project can name its own achievements without editing the\n\
         engine. One kind is the engine's, because the thing it reaches is inside the\n\
         engine and nothing else in the process can get at it:\n\n\
         ```lua\n\
         event.emit(\"audio.bus_volume\", { bus = \"Music\", percent = 80 })\n\
         ```\n\n\
         | Field | Meaning |\n\
         |---|---|\n\
         | `bus` | `\"Music\"`, `\"Sfx\"` or `\"Ui\"` |\n\
         | `percent` | A whole number, 0 to 100. `0` is **silent** |\n\n\
         Percent, and whole, because a setting a player chose is a number of steps on a\n\
         slider and the determinism lint rightly refuses a float literal in Lua. It is\n\
         mapped onto decibels rather than onto amplitude — loudness is logarithmic, so a\n\
         linear gain makes halfway up already most of the way loud — over a 40 dB range,\n\
         which gives a five-step control five evenly spaced steps. Zero is silent by its\n\
         own case, because a logarithmic scale has no bottom. The change is made over a\n\
         short fade, so stepping a slider is heard as a change rather than a click.\n\n\
         The runtime applies it; the **game still owns the setting**. Keep it in the\n\
         profile and emit it on launch and on every change, which is what makes this\n\
         one-way channel enough — see above for why the host does not talk back.\n\n\
         A kind the engine claims with a payload it cannot read is `DIM1103`, because the\n\
         game asked for something and did not get it. A kind it does not claim is not a\n\
         diagnostic at all: it belongs to whoever drained the list.\n\n\
         A headless run has no device, so `dim run` reports these and applies nothing. A\n\
         replay must not apply them either, for the same reason it ignores `app.quit()`.\n\n\
         ### Saves and the profile\n\n\
         Two kinds of persistence, and conflating them is the bug.\n\n\
         A **run** is simulation state. `dim state save` writes one and `dim state load`\n\
         reads it back, exactly: the resumed run continues identically, RNG streams\n\
         included, or it is a different run. The tree goes out as canonical `.dim` text\n\
         rather than a second serialisation, because I2 already guarantees that\n\
         round-trips, and a save that is text is a save somebody can read. A save from\n\
         a different engine version is **refused** (`DIM1002`) rather than warned about:\n\
         a log that replays wrong announces itself as a divergence, while a save that\n\
         restores wrong just keeps playing.\n\n\
         A **profile** is what accumulates across runs -- knowledge, awards, unlocks.\n\
         It is reached through `profile.get`, `profile.put` and `profile.clear`, and it\n\
         is **not in `SimState` at all**. Not a field the hasher skips: absent, the way\n\
         the log lines are, because kept-out-entirely is one fewer thing to get wrong.\n\
         Two players on the same seed have different profiles, so a hashed one would\n\
         make their replays diverge for a reason that has nothing to do with the game.\n\
         It is not snapshotted either, so a rollback does not take back an award.\n\n\
         **The hazard this cannot fix.** Keeping the profile out of the hash stops it\n\
         *being* hashed; it does not stop a script reading from it and writing what it\n\
         read into state. A line like `if profile.get(k) then self.spell = 1 end` makes\n\
         two players\' simulations differ, and hashing the profile would not help -- it\n\
         would turn a silent divergence into a loud one at the cost of making every\n\
         replay depend on who is playing. So the rule is one a game has to follow: **a\n\
         profile value may decide what is drawn, offered or unlocked, and may not decide\n\
         what the simulation does.** Choose a loadout from it at the menu, before the\n\
         run begins, and carry the choice in through `scene.request_load`, where it is\n\
         hashed like everything else.\n\n\
         ### Tiles\n\n\
         `tiles` reads and writes a `TileLayer`\'s grid while the game runs, which is\n\
         what a generated map needs: a roguelike builds its floor when you arrive from\n\
         the run\'s seed, and authoring floors as `.dim` files is the genre\'s negation.\n\n\
         **Writes are deferred to the end of the tick**, like `scene.spawn`, because a\n\
         script that changed the grid mid-tick would change it under every script that\n\
         had not run yet — and which terrain a monster saw would depend on where it fell\n\
         in the traversal. The useful consequence is that **reads need no snapshot**:\n\
         the grid does not change inside a tick at all, so a read during one is already\n\
         the grid as it stood when the tick began.\n\n\
         A cell nobody has painted reads as tile `0` rather than failing. A generator\n\
         checks the neighbours of an edge cell constantly, and an error for that would\n\
         mean bounds-checking every read. `tiles.bounds` reports where a layer has\n\
         storage, at chunk granularity, which is what a generator wants to iterate.\n\n\
         Tiles are part of the scene and the scene is hashed, so a painted tile moves\n\
         the state hash and a rollback rewinds the grid. A floor generated from a seed\n\
         therefore comes out identical on every machine, which is what makes a\n\
         generation bug arrive as a seed.\n\n\
         This does **not** go through the command bus, and that is deliberate rather\n\
         than an omission. The bus is the authoring path: a `SceneDoc` carries a TOML\n\
         document beside the model and a command keeps the two in step so a file can be\n\
         written back and undone. A running simulation has no document, and every tick\n\
         already moves nodes without a command in sight — `scene.spawn` does not use the\n\
         bus either. What *is* shared with the bus is the chunk handling, which lives in\n\
         `dimetric_scene::chunk` and has one implementation.\n\n\
         ### UI\n\n\
         `ui` reads what the pointer is doing to the interface, worked out inside the\n\
         tick — layout and hit testing run in a `UiUpdate` phase before scripts, so a\n\
         click on a menu is replayable like any other input. `ui.clicked(node)` is true\n\
         on the one tick a press and a release completed on that control; sliding off\n\
         before letting go cancels it.\n\n\
         **`ui.pointer()` is a canvas pixel, not a world position.** The canvas is the\n\
         fixed virtual resolution the project declares in `project.toml`, scaled to\n\
         whatever window the game gets — so the value is the same on every monitor,\n\
         which is what makes a recorded click land on the same button when it replays.\n\
         Getting from there to a world position means inverting the camera; see\n\
         `camera.to_world`.\n\n\
         `ui.captured()` is reported rather than enforced: the engine will not silently\n\
         swallow a click that landed on a control, because a script that never asked\n\
         would have no way to find out why its fire button stopped working over a menu.\n\n\
         Focus is tracked, not driven. `ui.focus_next(step)` walks the focusable\n\
         controls in tree order, and *which key* walks a menu is the game\'s decision —\n\
         binding it here would mean the engine deciding that pressing Down in a menu\n\
         can never also move the player.\n\n\
         ### A table read back from script state is a copy\n\n\
         A script variable holding a table is converted to a *fresh* Lua table on every\n\
         read. So this does nothing:\n\n\
         ```lua\n\
         self.bag.b = 2        -- lands in a temporary and is dropped\n\
         ```\n\n\
         and this is how to change one:\n\n\
         ```lua\n\
         local bag = self.bag\n\
         bag.b = 2\n\
         self.bag = bag\n\
         ```\n\n\
         The copy is what keeps the hashed state authoritative — a Lua table aliasing it\n\
         could write past a snapshot. `dim script check --determinism` reports the first\n\
         form as `DIM0507`, with the file, the line and the variable, because it cannot\n\
         be caught at the write: a metatable on a table sees only keys that are absent,\n\
         and `docs/ENGINE-GAPS.md` has the rest of the argument.\n\n\
         ### Images in the UI\n\n\
         `TextureRect` is a `Control` that draws a texture at its own rectangle: the\n\
         same anchors, offsets and hit testing every other control has, plus `texture`,\n\
         `region`, `modulate`, the flips and a blend mode. It is drawn by the UI walk in\n\
         tree order with the panels around it, out of the atlas the world pass already\n\
         uses, so it costs no pass and no pipeline of its own.\n\n\
         It **fills** its rectangle rather than keeping the texture\'s aspect. A\n\
         control\'s size is what its anchors and offsets say, and a node that quietly\n\
         ignored them would not be a control.\n\n\
         An imported animation works in one too: `animation`, `playing` and the engine\n\
         -written `frame` behave as they do on an `AnimatedSprite2D`, and `anim.play`\n\
         and `anim.restart` reach it. A `Sprite2D` under a control is still drawn by the\n\
         *world* pass, at a world position under the camera — which is almost never what\n\
         a HUD wants.\n\n\
         ### Tweens and animation\n\n\
         Tweens and animation are simulation state, not presentation. They advance on\n\
         ticks, they are snapshotted, and they are in the state hash — a tween outside\n\
         the hash could not survive a rollback, and would be left mid-flight writing to\n\
         positions that had just been rewound. Easing runs in fixed point for the same\n\
         reason everything else does. The easings are `linear`, `ease_in`, `ease_out`\n\
         and `ease_in_out`; `pos`, `scale`, `rot` and any scalar, vector, angle or\n\
         colour property can be tweened.\n\n\
         Animation clips come from the importer with their frame durations already in\n\
         ticks. `on_anim_event(self, name)` fires when playback reaches a frame that\n\
         carries an event, which is how a hitbox opens on the swing frame rather than\n\
         on a timer someone has to keep in sync by hand.\n\n\
         An `AnimatedSprite2D` has two ways to say what it is playing and they are one\n\
         thing: `anim.play(node, clip)` writes the node\'s `animation` property, so the\n\
         node carries what it is playing and a save round-trips to the same clip.\n\
         Authoring `animation` in the scene is the same change made by hand.\n\n\
         `anim.play` of the clip already running is deliberately **not** a restart, so\n\
         calling it every tick is harmless. `anim.restart(node)` is the restart: frame\n\
         zero, not finished, playing. Without it a non-looping clip that had finished\n\
         stayed on its last frame for the life of the node, which is a pooled effect\n\
         sprite that plays once and then shows the final frame forever.\n\n\
         ### Sound\n\n\
         `node:play()` on a `Sound` node asks for its clip; `node:stop()` stops what\n\
         that node started. The script says *when* and the node's properties say what,\n\
         on which bus, how loud and how far the pitch wanders — so an instance override\n\
         can change a sound and a designer can find it.\n\n\
         **`continuous = true` survives a scene load.** A floor change swaps the whole\n\
         tree, and a voice whose node has left it is stopped — which is right for a\n\
         projectile\'s loop and wrong for a region theme, so music restarted from bar one\n\
         on every floor. A continuous voice is keyed by its stream and bus rather than by\n\
         its node: the next scene\'s own copy of the same track finds it sounding and\n\
         continues it, a different track on the same bus replaces it (the outgoing one\n\
         fades, so it cross-fades), and `node:stop()` still stops it.\n\n\
         A floor that has no node asking for the track loses it, on the tick the swap\n\
         happens. The question is asked of the *scene* rather than of a timer, so there is\n\
         no interval to tune and no window in which music plays over a floor that did not\n\
         want it.\n\n\
         A node id that is still in the tree but now belongs to a **different** node is\n\
         reported (`DIM1102`) and its voice stopped. Two scene files reusing an id — easy\n\
         when ids come from a generator — would otherwise leave a voice attached to\n\
         whatever landed on that id, and two tracks would play at once.\n\n\
         The simulation never plays anything. It appends to a list that is cleared at\n\
         the start of every tick and **is not hashed**, and whoever is listening reads\n\
         it. If a trigger consumed a random number or wrote hashed state, muting a game\n\
         would change how it plays and a run recorded with audio on would diverge from\n\
         one played with it off. `dim run` reports how many sounds a headless run asked\n\
         for.\n\n\
         ### Modules\n\n\
         `require(\"scripts/spellbook.lua\")` runs that script once and hands back\n\
         what it returned — the project-relative path a scene would write after\n\
         `script:`, one spelling rather than several to guess between. Every\n\
         script in a project is loaded before any of them runs, so requiring one\n\
         does not depend on where its name falls in the alphabet, and a cycle is\n\
         an error naming the loop.\n\n\
         What comes back is **read-only, all the way down**. A module's table is\n\
         not part of the state: it is not hashed, not snapshotted and not\n\
         rewound, so anything written into it would survive a rollback that\n\
         rewound everything around it — a divergence that surfaces hours later\n\
         in a replay rather than at the write. A module holds constants and pure\n\
         functions; state belongs in node variables, where the hash can see it.\n\
         The engine enforces the first part and not the second: a module\n\
         function that closes over a local and mutates it is out of reach of any\n\
         guard, and is the one way left to hide state from the hash.\n\n\
         Reloading a module re-runs every script, because a script that required\n\
         it is holding the table it returned and reloading one file would leave\n\
         that script reading the previous version's constants.\n\n\
         ### The rule that matters\n\n\
         Lua numbers are `f64`. Gameplay arithmetic done in raw Lua numbers and written\n\
         into simulation state is the easiest way to break replay. Use `vec2` and `fx`\n\
         values, which do their arithmetic in fixed point.\n\n\
         The sandbox has no `os`, `io`, `dofile`, `load` or `package`, and no\n\
         `math.random` — randomness comes from a seeded `rng` stream. `math.sin` and the\n\
         other transcendental functions are also absent, because platform maths libraries\n\
         do not agree with each other; use `fx.sin` and `fx.cos`, which read committed\n\
         lookup tables. `rawset` is absent too: it writes past a `__newindex`, which is\n\
         the guard holding a required module read-only.\n",
    );
    Ok(out)
}
