//! Regenerates the committed trig tables.
//!
//! The tables are generated **once** and checked in. They are deliberately not
//! built by a `build.rs`, because that would run the host's `libm` on every
//! machine, and `sin` is not guaranteed bit-identical across platforms. One
//! differing low bit is a replay that diverges on someone else's computer.
//!
//! Run this only when changing the table resolution, and commit the result.

use std::fmt::Write as _;

/// Entries in the quarter-turn sine table, plus one endpoint.
const SIN_ENTRIES: usize = 1024;
/// Entries in the `atan(x)` table over `x` in `[0, 1]`, plus one endpoint.
const ATAN_ENTRIES: usize = 256;

pub fn run() -> Result<(), String> {
    let mut out = String::new();
    out.push_str(
        "//! Generated by `cargo xtask gen-trig`. Do not hand-edit.\n\
         //!\n\
         //! Committed rather than built, so every platform reads identical\n\
         //! numbers. See the module docs in `xtask/src/gen_trig.rs`.\n\n",
    );

    writeln!(
        out,
        "/// Quarter-turn sine, scaled by 65536. Index `i` is the angle\n\
         /// `i / {} ` of a full turn. The extra entry is the endpoint at 90°.\n\
         pub(crate) static SIN_Q: [i32; {}] = [",
        SIN_ENTRIES * 4,
        SIN_ENTRIES + 1
    )
    .unwrap();
    for i in 0..=SIN_ENTRIES {
        let turns = i as f64 / (SIN_ENTRIES * 4) as f64;
        let v = (turns * std::f64::consts::TAU).sin() * 65536.0;
        writeln!(out, "    {},", round_half_away(v)).unwrap();
    }
    out.push_str("];\n\n");

    writeln!(
        out,
        "/// `atan(i / {})` in binary angle units (65536 per turn).\n\
         /// The last entry is `atan(1)`, which is exactly an eighth of a turn.\n\
         pub(crate) static ATAN_UNIT: [i32; {}] = [",
        ATAN_ENTRIES,
        ATAN_ENTRIES + 1
    )
    .unwrap();
    for i in 0..=ATAN_ENTRIES {
        let x = i as f64 / ATAN_ENTRIES as f64;
        let v = x.atan() / std::f64::consts::TAU * 65536.0;
        writeln!(out, "    {},", round_half_away(v)).unwrap();
    }
    out.push_str("];\n");

    let path = crate::workspace_root().join("crates/dimetric-core/src/trig_table.rs");
    std::fs::write(&path, out).map_err(|e| format!("writing {}: {e}", path.display()))?;
    eprintln!("xtask: wrote {}", path.display());
    Ok(())
}

fn round_half_away(v: f64) -> i64 {
    if v >= 0.0 {
        (v + 0.5).floor() as i64
    } else {
        (v - 0.5).ceil() as i64
    }
}
