//! Regenerates `docs/API.md` and `docs/schemas/`.
//!
//! Generated from the engine itself, by asking the `dim` binary, rather than
//! written by hand. Invariant I10 asks for a documented, versioned contract for
//! every command and binding; a contract maintained by hand is a contract that
//! is wrong by the second release, and an agent reading a stale one writes
//! confident code against an API that no longer exists.
//!
//! The artifacts are committed so that contributors and agents read the same
//! source of truth — a rare case where two audiences want identical files.

use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

pub fn run() -> Result<(), String> {
    let root = crate::workspace_root();
    let docs = root.join("docs");
    let schemas = docs.join("schemas");
    std::fs::create_dir_all(&schemas).map_err(|e| format!("creating docs/schemas: {e}"))?;

    let codes = dim(&root, &["api", "codes", "--json"])?;
    let kinds = dim(&root, &["api", "kinds", "--json"])?;
    let commands = dim(&root, &["api", "schema", "--json"])?;
    let tools = dim(&root, &["api", "tools", "--json"])?;

    write_json(&schemas.join("diagnostics.json"), &codes)?;
    write_json(&schemas.join("node-kinds.json"), &kinds)?;
    write_json(&schemas.join("commands.json"), &commands)?;
    write_json(&schemas.join("mcp-tools.json"), &tools)?;

    let markdown = render_markdown(&codes, &kinds, &commands, &tools)?;
    let path = docs.join("API.md");
    std::fs::write(&path, markdown).map_err(|e| format!("writing {}: {e}", path.display()))?;
    eprintln!("xtask: wrote docs/API.md and docs/schemas/");
    Ok(())
}

/// Run the `dim` binary and return its JSON result.
fn dim(root: &Path, args: &[&str]) -> Result<serde_json::Value, String> {
    let output = Command::new(env!("CARGO"))
        .current_dir(root)
        .args(["run", "--quiet", "-p", "dimetric-agent", "--"])
        .args(args)
        .output()
        .map_err(|e| format!("running dim {}: {e}", args.join(" ")))?;
    if !output.status.success() {
        return Err(format!(
            "dim {} failed:\n{}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let envelope: serde_json::Value = serde_json::from_str(&text)
        .map_err(|e| format!("dim {} gave invalid JSON: {e}", args.join(" ")))?;
    Ok(envelope
        .get("result")
        .cloned()
        .unwrap_or(serde_json::Value::Null))
}

fn write_json(path: &Path, value: &serde_json::Value) -> Result<(), String> {
    let text = serde_json::to_string_pretty(value)
        .map_err(|e| format!("serializing {}: {e}", path.display()))?;
    std::fs::write(path, format!("{text}\n"))
        .map_err(|e| format!("writing {}: {e}", path.display()))
}

fn render_markdown(
    codes: &serde_json::Value,
    kinds: &serde_json::Value,
    commands: &serde_json::Value,
    tools: &serde_json::Value,
) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(
        "# Dimetric API reference\n\n\
         Generated by `cargo xtask gen-docs`. Do not hand-edit — your changes will be\n\
         overwritten, and the point of generating it is that it cannot disagree with the\n\
         code.\n\n\
         Machine-readable versions of everything below are in `docs/schemas/`.\n\n",
    );

    // -- commands --------------------------------------------------------
    out.push_str(
        "## Commands\n\n\
         Every mutation the engine can perform. The editor, the CLI and an agent all go\n\
         through this list and nothing else (invariant I1). Commands marked undoable go on\n\
         the undo stack; the rest act on the project rather than the open scene.\n\n\
         | Command | Fields | Undoable |\n|---|---|---|\n",
    );
    let list = commands
        .get("commands")
        .and_then(|c| c.as_array())
        .ok_or("command schema has no `commands` array")?;
    for command in list {
        let name = command.get("name").and_then(|v| v.as_str()).unwrap_or("?");
        let fields = command
            .get("fields")
            .and_then(|f| f.as_array())
            .map(|f| {
                f.iter()
                    .filter_map(|v| v.as_str())
                    .map(|s| format!("`{s}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            })
            .unwrap_or_default();
        let undoable = command
            .get("undoable")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let _ = writeln!(
            out,
            "| `{name}` | {} | {} |",
            if fields.is_empty() {
                "—".into()
            } else {
                fields
            },
            if undoable { "yes" } else { "no" }
        );
    }

    // -- node kinds ------------------------------------------------------
    out.push_str(
        "\n## Node kinds\n\n\
         A node's `kind` selects the schema its properties are validated against. Unknown\n\
         properties are a hard error (`DIM0301`), so a kind must register before its\n\
         scenes will load — which is also what makes the \"did you mean\" suggestion\n\
         possible.\n\n\
         Properties equal to their default are omitted from the file and filled in on\n\
         load, so a scene does not grow every time a kind gains a property.\n",
    );
    let kind_list = kinds
        .get("kinds")
        .and_then(|k| k.as_array())
        .ok_or("kind schema has no `kinds` array")?;
    for kind in kind_list {
        let name = kind.get("kind").and_then(|v| v.as_str()).unwrap_or("?");
        let doc = kind.get("doc").and_then(|v| v.as_str()).unwrap_or("");
        let _ = write!(out, "\n### `{name}`\n\n{doc}\n\n");
        let properties = kind
            .get("properties")
            .and_then(|p| p.as_array())
            .cloned()
            .unwrap_or_default();
        if properties.is_empty() {
            out.push_str("No properties beyond the reserved keys.\n");
            continue;
        }
        out.push_str("| Property | Type | Default | Notes |\n|---|---|---|---|\n");
        for property in properties {
            let field = |key: &str| {
                property
                    .get(key)
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string()
            };
            let required = property
                .get("required")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let default = property
                .get("default")
                .and_then(|v| v.as_str())
                .map(|d| format!("`{d}`"))
                .unwrap_or_else(|| {
                    if required {
                        "**required**".into()
                    } else {
                        "—".into()
                    }
                });
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {default} | {} |",
                field("name"),
                field("type"),
                field("doc").replace('|', "\\|")
            );
        }
    }

    // -- diagnostics -----------------------------------------------------
    out.push_str(
        "\n## Diagnostic codes\n\n\
         Every failure carries one of these, plus a source location and a\n\
         machine-readable payload (invariant I9). Match on the code; never parse the\n\
         message. Codes are never reused for a different meaning.\n\n\
         | Code | Severity | Meaning |\n|---|---|---|\n",
    );
    let code_list = codes
        .get("codes")
        .and_then(|c| c.as_array())
        .ok_or("diagnostics have no `codes` array")?;
    for code in code_list {
        let field = |key: &str| code.get(key).and_then(|v| v.as_str()).unwrap_or("");
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            field("code"),
            field("severity"),
            field("summary")
        );
    }

    // -- mcp tools -------------------------------------------------------
    out.push_str(
        "\n## MCP tools\n\n\
         `dim mcp` serves the CLI over the Model Context Protocol. The tools are read\n\
         from the CLI itself, so this list is what the binary answers `tools/list` with.\n\
         `project`, `scene`, `json` and `id_seed` are global and omitted from the\n\
         arguments column.\n\n\
         | Tool | Arguments | What it does |\n|---|---|---|\n",
    );
    let globals = ["project", "scene", "json", "id_seed"];
    let list = tools
        .get("tools")
        .and_then(|t| t.as_array())
        .ok_or("api tools gave no list")?;
    for tool in list {
        let name = tool
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let about = tool
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let schema = &tool["inputSchema"];
        let required: Vec<&str> = schema
            .get("required")
            .and_then(|r| r.as_array())
            .map(|r| r.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        let mut arguments: Vec<String> = schema
            .get("properties")
            .and_then(|p| p.as_object())
            .map(|p| p.keys().cloned().collect())
            .unwrap_or_default();
        arguments.retain(|a| !globals.contains(&a.as_str()));
        arguments.sort();
        let rendered: Vec<String> = arguments
            .iter()
            .map(|a| {
                if required.contains(&a.as_str()) {
                    format!("`{a}`*")
                } else {
                    format!("`{a}`")
                }
            })
            .collect();
        let _ = writeln!(
            out,
            "| `{name}` | {} | {about} |",
            if rendered.is_empty() {
                "—".to_string()
            } else {
                rendered.join(", ")
            }
        );
    }
    out.push_str("\nAn argument marked `*` is required.\n");

    out.push_str(
        "\n## Lua API\n\n\
         Scripts see exactly these globals and nothing else.\n\n\
         | Global | What it gives you |\n|---|---|\n\
         | `scene` | `find(path)`, `by_id(id)`, `tagged(tag)`, `near(at, radius, tag)`, `nearest(at, radius, tag)`, `spawn(prefab, at, parent)` |\n\
         | `input` | `move()`, `aim()`, `aim_vector()`, `held(button)`, `pressed(button)`, `released(button)` |\n\
         | `tick` | `count()`, `dt()`, `rate` |\n\
         | `rng` | `range(stream, lo, hi)`, `chance(stream, n, d)`, `unit(stream)` |\n\
         | `vec2` | `vec2(x, y)`, building a fixed-point vector |\n\
         | `fx` | `new`, `parse`, `sin`, `cos`, `from_angle` |\n\
         | `log` | `info`, `warn`, `error` — collected per tick, never hashed |\n\
         | `tween` | `to(node, property, target, ticks, easing)`, `cancel(node, property)`, `running(node, property)` |\n\
         | `require` | `require(path)`, another script's returned table |\n\
         | `anim` | `play(node, clip)`, `stop(node)`, `frame(node)`, `playing(node)`, `finished(node)` |\n\n\
         A node handle supports `get`, `set`, `find`, `parent`, `children`, `emit`,\n\
         `destroy`, `set_velocity`, `velocity`, `world_pos`, `has_tag`, `name`, `path`,\n\
         `kind`, `valid`, and — on a `Sound` node — `play` and `stop`. Indexing a handle\n\
         reads and writes script variables, except for `pos`, `rot` and `visible`, which\n\
         reach the node's transform.\n\n\
         ### Spawning\n\n\
         `scene.spawn` returns the id the node *will* have and creates nothing yet.\n\
         A node inserted mid-tick would be going into a tree another script may be\n\
         walking, so spawns are applied at the end of the tick and the node gets\n\
         `on_ready` on the next one. The id is derived from a counter in the state\n\
         rather than drawn from the RNG, which is what makes it the same on every\n\
         machine and the same again after a rollback — and means spawning one fewer\n\
         projectile does not shift every gameplay roll after it.\n\n\
         `scene.near` and `scene.nearest` read the broadphase as it stood at the\n\
         *start* of the tick, so every script sees the same world and what one finds\n\
         does not depend on whether another has run yet.\n\n\
         ### Tweens and animation\n\n\
         Tweens and animation are simulation state, not presentation. They advance on\n\
         ticks, they are snapshotted, and they are in the state hash — a tween outside\n\
         the hash could not survive a rollback, and would be left mid-flight writing to\n\
         positions that had just been rewound. Easing runs in fixed point for the same\n\
         reason everything else does. The easings are `linear`, `ease_in`, `ease_out`\n\
         and `ease_in_out`; `pos`, `scale`, `rot` and any scalar, vector, angle or\n\
         colour property can be tweened.\n\n\
         Animation clips come from the importer with their frame durations already in\n\
         ticks. `on_anim_event(self, name)` fires when playback reaches a frame that\n\
         carries an event, which is how a hitbox opens on the swing frame rather than\n\
         on a timer someone has to keep in sync by hand.\n\n\
         ### Sound\n\n\
         `node:play()` on a `Sound` node asks for its clip; `node:stop()` stops what\n\
         that node started. The script says *when* and the node's properties say what,\n\
         on which bus, how loud and how far the pitch wanders — so an instance override\n\
         can change a sound and a designer can find it.\n\n\
         The simulation never plays anything. It appends to a list that is cleared at\n\
         the start of every tick and **is not hashed**, and whoever is listening reads\n\
         it. If a trigger consumed a random number or wrote hashed state, muting a game\n\
         would change how it plays and a run recorded with audio on would diverge from\n\
         one played with it off. `dim run` reports how many sounds a headless run asked\n\
         for.\n\n\
         ### Modules\n\n\
         `require(\"scripts/spellbook.lua\")` runs that script once and hands back\n\
         what it returned — the project-relative path a scene would write after\n\
         `script:`, one spelling rather than several to guess between. Every\n\
         script in a project is loaded before any of them runs, so requiring one\n\
         does not depend on where its name falls in the alphabet, and a cycle is\n\
         an error naming the loop.\n\n\
         What comes back is **read-only, all the way down**. A module's table is\n\
         not part of the state: it is not hashed, not snapshotted and not\n\
         rewound, so anything written into it would survive a rollback that\n\
         rewound everything around it — a divergence that surfaces hours later\n\
         in a replay rather than at the write. A module holds constants and pure\n\
         functions; state belongs in node variables, where the hash can see it.\n\
         The engine enforces the first part and not the second: a module\n\
         function that closes over a local and mutates it is out of reach of any\n\
         guard, and is the one way left to hide state from the hash.\n\n\
         Reloading a module re-runs every script, because a script that required\n\
         it is holding the table it returned and reloading one file would leave\n\
         that script reading the previous version's constants.\n\n\
         ### The rule that matters\n\n\
         Lua numbers are `f64`. Gameplay arithmetic done in raw Lua numbers and written\n\
         into simulation state is the easiest way to break replay. Use `vec2` and `fx`\n\
         values, which do their arithmetic in fixed point.\n\n\
         The sandbox has no `os`, `io`, `dofile`, `load` or `package`, and no\n\
         `math.random` — randomness comes from a seeded `rng` stream. `math.sin` and the\n\
         other transcendental functions are also absent, because platform maths libraries\n\
         do not agree with each other; use `fx.sin` and `fx.cos`, which read committed\n\
         lookup tables. `rawset` is absent too: it writes past a `__newindex`, which is\n\
         the guard holding a required module read-only.\n",
    );
    Ok(out)
}
