//! Regenerates `docs/API.md` and `docs/schemas/`.
//!
//! Generated from the engine itself, by asking the `dim` binary, rather than
//! written by hand. Invariant I10 asks for a documented, versioned contract for
//! every command and binding; a contract maintained by hand is a contract that
//! is wrong by the second release, and an agent reading a stale one writes
//! confident code against an API that no longer exists.
//!
//! The artifacts are committed so that contributors and agents read the same
//! source of truth — a rare case where two audiences want identical files.

use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

pub fn run() -> Result<(), String> {
    let root = crate::workspace_root();
    let docs = root.join("docs");
    let schemas = docs.join("schemas");
    std::fs::create_dir_all(&schemas).map_err(|e| format!("creating docs/schemas: {e}"))?;

    let codes = dim(&root, &["api", "codes", "--json"])?;
    let kinds = dim(&root, &["api", "kinds", "--json"])?;
    let commands = dim(&root, &["api", "schema", "--json"])?;
    let tools = dim(&root, &["api", "tools", "--json"])?;
    let lua_globals = dim(&root, &["api", "globals", "--json"])?;
    let reserved = dim(&root, &["api", "reserved", "--json"])?;
    let ids = dim(&root, &["api", "ids", "--json"])?;

    write_json(&schemas.join("diagnostics.json"), &codes)?;
    write_json(&schemas.join("node-kinds.json"), &kinds)?;
    write_json(&schemas.join("commands.json"), &commands)?;
    write_json(&schemas.join("mcp-tools.json"), &tools)?;

    let markdown = render_markdown(
        &codes,
        &kinds,
        &commands,
        &tools,
        &lua_globals,
        &reserved,
        &ids,
    )?;
    let path = docs.join("API.md");
    std::fs::write(&path, markdown).map_err(|e| format!("writing {}: {e}", path.display()))?;
    eprintln!("xtask: wrote docs/API.md and docs/schemas/");
    Ok(())
}

/// Run the `dim` binary and return its JSON result.
fn dim(root: &Path, args: &[&str]) -> Result<serde_json::Value, String> {
    let output = Command::new(env!("CARGO"))
        .current_dir(root)
        .args(["run", "--quiet", "-p", "dimetric-agent", "--"])
        .args(args)
        .output()
        .map_err(|e| format!("running dim {}: {e}", args.join(" ")))?;
    if !output.status.success() {
        return Err(format!(
            "dim {} failed:\n{}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let envelope: serde_json::Value = serde_json::from_str(&text)
        .map_err(|e| format!("dim {} gave invalid JSON: {e}", args.join(" ")))?;
    Ok(envelope
        .get("result")
        .cloned()
        .unwrap_or(serde_json::Value::Null))
}

/// Squeeze runs of whitespace into single spaces.
fn collapse(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn write_json(path: &Path, value: &serde_json::Value) -> Result<(), String> {
    let text = serde_json::to_string_pretty(value)
        .map_err(|e| format!("serializing {}: {e}", path.display()))?;
    std::fs::write(path, format!("{text}\n"))
        .map_err(|e| format!("writing {}: {e}", path.display()))
}

fn render_markdown(
    codes: &serde_json::Value,
    kinds: &serde_json::Value,
    commands: &serde_json::Value,
    tools: &serde_json::Value,
    lua_globals: &serde_json::Value,
    reserved: &serde_json::Value,
    ids: &serde_json::Value,
) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(
        "# Dimetric API reference\n\n\
         Generated by `cargo xtask gen-docs`. Do not hand-edit — your changes will be\n\
         overwritten, and the point of generating it is that it cannot disagree with the\n\
         code.\n\n\
         Machine-readable versions of everything below are in `docs/schemas/`.\n\n",
    );

    // -- commands --------------------------------------------------------
    out.push_str(
        "## Commands\n\n\
         Every mutation the engine can perform. The editor, the CLI and an agent all go\n\
         through this list and nothing else (invariant I1). Commands marked undoable go on\n\
         the undo stack; the rest act on the project rather than the open scene.\n\n\
         | Command | Fields | Undoable |\n|---|---|---|\n",
    );
    let list = commands
        .get("commands")
        .and_then(|c| c.as_array())
        .ok_or("command schema has no `commands` array")?;
    for command in list {
        let name = command.get("name").and_then(|v| v.as_str()).unwrap_or("?");
        let fields = command
            .get("fields")
            .and_then(|f| f.as_array())
            .map(|f| {
                f.iter()
                    .filter_map(|v| v.as_str())
                    .map(|s| format!("`{s}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            })
            .unwrap_or_default();
        let undoable = command
            .get("undoable")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let _ = writeln!(
            out,
            "| `{name}` | {} | {} |",
            if fields.is_empty() {
                "—".into()
            } else {
                fields
            },
            if undoable { "yes" } else { "no" }
        );
    }

    // -- node kinds ------------------------------------------------------
    out.push_str(
        "\n## Node kinds\n\n\
         A node's `kind` selects the schema its properties are validated against. Unknown\n\
         properties are a hard error (`DIM0301`), so a kind must register before its\n\
         scenes will load — which is also what makes the \"did you mean\" suggestion\n\
         possible.\n\n\
         Properties equal to their default are omitted from the file and filled in on\n\
         load, so a scene does not grow every time a kind gains a property.\n",
    );

    // The keys every node carries, which the per-kind tables below do *not*
    // repeat. Generated from `dimetric_scene::schema::RESERVED_KEY_DOCS`,
    // with a test in that crate holding it against `RESERVED_KEYS`, because
    // this reference spent four milestones referring to "the reserved keys"
    // without listing them anywhere.
    out.push_str(
        "\n### Keys every node has\n\n\
         These sit on every node whatever its kind, and a kind may not declare a\n\
         property that shadows one (`DIM0104`). They are *not* repeated in the\n\
         per-kind tables below.\n\n\
         | Key | What it does |\n|---|---|\n",
    );
    for key in reserved["reserved"].as_array().into_iter().flatten() {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            key["name"].as_str().unwrap_or_default(),
            // The source strings wrap with Rust's `\` continuation, which keeps
            // the next line's indentation. Harmless in a doc comment, a run of
            // spaces in the middle of a table cell here.
            collapse(key["doc"].as_str().unwrap_or_default())
        );
    }
    out.push_str(
        "\nDraw order sorts on `layer` first, then `z`, then depth, then whatever the\n\
         batcher splits on, and finally the node id so that no two sprites are ever in\n\
         an ambiguous order. Depth is the world position under the current projection,\n\
         quantised to whole units so a sprite drifting by a fraction of a pixel cannot\n\
         flicker past its neighbour. **Nudging a sprite\'s position to force it in front\n\
         of another is never the answer** — that is what `z` and `layer` are for.\n",
    );
    let kind_list = kinds
        .get("kinds")
        .and_then(|k| k.as_array())
        .ok_or("kind schema has no `kinds` array")?;
    for kind in kind_list {
        let name = kind.get("kind").and_then(|v| v.as_str()).unwrap_or("?");
        let doc = kind.get("doc").and_then(|v| v.as_str()).unwrap_or("");
        let _ = write!(out, "\n### `{name}`\n\n{doc}\n\n");
        let properties = kind
            .get("properties")
            .and_then(|p| p.as_array())
            .cloned()
            .unwrap_or_default();
        if properties.is_empty() {
            out.push_str("No properties beyond the reserved keys.\n");
            continue;
        }
        out.push_str("| Property | Type | Default | Notes |\n|---|---|---|---|\n");
        for property in properties {
            let field = |key: &str| {
                property
                    .get(key)
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string()
            };
            let required = property
                .get("required")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let default = property
                .get("default")
                .and_then(|v| v.as_str())
                .map(|d| format!("`{d}`"))
                .unwrap_or_else(|| {
                    if required {
                        "**required**".into()
                    } else {
                        "—".into()
                    }
                });
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {default} | {} |",
                field("name"),
                field("type"),
                field("doc").replace('|', "\\|")
            );
        }
    }

    // -- diagnostics -----------------------------------------------------
    out.push_str(
        "\n## Diagnostic codes\n\n\
         Every failure carries one of these, plus a source location and a\n\
         machine-readable payload (invariant I9). Match on the code; never parse the\n\
         message. Codes are never reused for a different meaning.\n\n\
         | Code | Severity | Meaning |\n|---|---|---|\n",
    );
    let code_list = codes
        .get("codes")
        .and_then(|c| c.as_array())
        .ok_or("diagnostics have no `codes` array")?;
    for code in code_list {
        let field = |key: &str| code.get(key).and_then(|v| v.as_str()).unwrap_or("");
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            field("code"),
            field("severity"),
            field("summary")
        );
    }

    // -- mcp tools -------------------------------------------------------
    out.push_str(
        "\n## MCP tools\n\n\
         `dim mcp` serves the CLI over the Model Context Protocol. The tools are read\n\
         from the CLI itself, so this list is what the binary answers `tools/list` with.\n\
         `project`, `scene`, `json` and `id_seed` are global and omitted from the\n\
         arguments column.\n\n\
         | Tool | Arguments | What it does |\n|---|---|---|\n",
    );
    let globals = ["project", "scene", "json", "id_seed"];
    let list = tools
        .get("tools")
        .and_then(|t| t.as_array())
        .ok_or("api tools gave no list")?;
    for tool in list {
        let name = tool
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let about = tool
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let schema = &tool["inputSchema"];
        let required: Vec<&str> = schema
            .get("required")
            .and_then(|r| r.as_array())
            .map(|r| r.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        let mut arguments: Vec<String> = schema
            .get("properties")
            .and_then(|p| p.as_object())
            .map(|p| p.keys().cloned().collect())
            .unwrap_or_default();
        arguments.retain(|a| !globals.contains(&a.as_str()));
        arguments.sort();
        let rendered: Vec<String> = arguments
            .iter()
            .map(|a| {
                if required.contains(&a.as_str()) {
                    format!("`{a}`*")
                } else {
                    format!("`{a}`")
                }
            })
            .collect();
        let _ = writeln!(
            out,
            "| `{name}` | {} | {about} |",
            if rendered.is_empty() {
                "—".to_string()
            } else {
                rendered.join(", ")
            }
        );
    }
    out.push_str("\nAn argument marked `*` is required.\n");

    // Generated from the manifest in `dimetric_sim::api_doc`, not typed here.
    // This section used to be a literal, and it drifted: M12 added the whole
    // `ui` global and the reference went on listing ten of eleven. A test in
    // `dimetric-sim` compares that manifest against a real sandbox, so the
    // table below cannot claim an API that does not exist, or miss one that
    // does.
    out.push_str("\n## Lua API\n\nScripts see exactly these globals and nothing else.\n\n");
    out.push_str("| Global | What it gives you |\n|---|---|\n");
    for global in lua_globals["globals"].as_array().into_iter().flatten() {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            global["name"].as_str().unwrap_or_default(),
            global["about"].as_str().unwrap_or_default()
        );
    }
    out.push_str(
        "\nPlus the parts of the Lua standard library the sandbox re-exports: \
         `assert`, `error`, `ipairs`, `next`, `pairs`, `pcall`, `select`, `tonumber`, \
         `tostring`, `type`, `xpcall`, `rawequal`, `rawget`, `rawlen`, `setmetatable`, \
         `getmetatable`, `string`, `table`, and a reduced `math` holding only the \
         exactly-defined integer operations. `rawset` is deliberately absent: it writes \
         past the `__newindex` that keeps a required module read-only.\n\n",
    );
    out.push_str(
        "A node handle supports `get`, `set`, `find`, `parent`, `children`, `emit`,\n\
         `destroy`, `set_velocity`, `velocity`, `world_pos`, `has_tag`, `name`, `path`,\n\
         `kind`, `valid`, and — on a `Sound` node — `play` and `stop`. Indexing a handle\n\
         reads and writes script variables, except for `pos`, `rot` and `visible`, which\n\
         reach the node's transform.\n\n\
         `self.thing = nil` clears a script variable, as it clears a key from any\n\
         other Lua table, and `self.thing` then reads back as `nil`. Nil is not a value\n\
         the engine stores, so anywhere else — `node:set`, `profile.put`, a tween\n\
         target — it is refused rather than turned into something else.\n\n\
         ### Reading a property and writing it back\n\n\
         `node:get` and `node:set` address the *kind properties* — the ones a kind's\n\
         schema declares. The keys every node has are not among them: they live on the\n\
         node itself, so `node:set(\"visible\", false)` would shadow the real one rather\n\
         than change it, and is refused with `DIM0104`. Write `self.visible = false`,\n\
         which reaches the node.\n\n\
         A write may not change a property's type (`DIM0505`). The authored value is\n\
         the type of record, because it came through the parser, which had the schema.\n\n\
         Four types reach a script as a string, because a string is how they are\n\
         written: a colour is `#rrggbbaa`, an angle is degrees, a reference is\n\
         `asset:sprites/bogling`, an enum is its variant. Writing one of those back is\n\
         *not* a type change — the text is re-read by the same parser the scene format\n\
         uses, so `node:set(k, node:get(k))` round-trips on every type, and text that\n\
         does not parse is refused with the reason rather than stored.\n\n\
         ### Colours\n\n\
         ```lua\n\
         bar:set(\"modulate\", color.rgba(255, 143, 74, 255))\n\
         bar:set(\"modulate\", color.rgb(255, 143, 74))   -- opaque, said aloud\n\
         bar:set(\"modulate\", \"#ff8f4aff\")              -- what `get` hands back\n\
         ```\n\n\
         Channels are bytes and are refused outside `0..255` rather than clamped: a\n\
         clamp makes a colour the author did not write and does not mention the\n\
         arithmetic that produced it. Alpha is explicit, here as in a `.dim` file —\n\
         `#ff8f4a` is not a colour in this engine, and `color.rgb` is how to mean\n\
         opaque. A colour is a node property, so it is hashed and replays like `pos`.\n\n\
         ### Spawning\n\n\
         `scene.spawn` returns the id the node *will* have and creates nothing yet.\n\
         A node inserted mid-tick would be going into a tree another script may be\n\
         walking, so spawns are applied at the end of the tick and the node gets\n\
         `on_ready` on the next one. The id is derived from a counter in the state\n\
         rather than drawn from the RNG, which is what makes it the same on every\n\
         machine and the same again after a rollback — and means spawning one fewer\n\
         projectile does not shift every gameplay roll after it.\n\n\
         `scene.near` and `scene.nearest` read the broadphase as it stood at the\n\
         *start* of the tick, so every script sees the same world and what one finds\n\
         does not depend on whether another has run yet.\n\n\
         ### Identifiers\n\n",
    );

    // Generated from `dimetric_core::id`, because anybody hand-writing or
    // generating a `.meta` has to know this and the only way to find it out
    // used to be reading `core/src/id.rs`. A generator that did not emitted
    // `sprites_ashfen_bogling`, and 84 sidecars were overwritten rather than
    // refused.
    let length = ids["length"].as_u64().unwrap_or_default();
    let _ = writeln!(
        out,
        "Every id is a prefix followed by exactly {length} characters.\n"
    );
    out.push_str("| Prefix | Identifies |\n|---|---|\n");
    for prefix in ids["prefixes"].as_array().into_iter().flatten() {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            prefix["prefix"].as_str().unwrap_or_default(),
            prefix["identifies"].as_str().unwrap_or_default()
        );
    }
    let _ = writeln!(
        out,
        "\nGenerated ids draw from `{}` — Crockford-style base32 with the characters \
         that are easy to misread removed. Parsing is more permissive and accepts any \
         of `[0-9a-z_]`, so a hand-written id may use an underscore; it may not be a \
         different length, and it may not omit the prefix.\n",
        ids["alphabet"].as_str().unwrap_or_default()
    );

    out.push_str(
        "\n### The `.meta` sidecar\n\n\
         An asset\'s settings live in a `<file>.meta` beside it, carrying its `id` and\n\
         how to import it. What happens to one the engine cannot use depends entirely\n\
         on whether it is **absent** or **malformed**, and the two are deliberately\n\
         different:\n\n\
         * **Absent** means no opinion. One is generated, with a derived id, and\n\
           written beside the source. Dropping a PNG into `assets/` and getting a\n\
           working sidecar is the intended way to add art.\n\
         * **Malformed** means an opinion that did not survive parsing. That asset\'s\n\
           import fails with `DIM0602` naming the file and the reason, and **the file\n\
           is left exactly as it is**. Fix it, or delete it to have one generated.\n\n\
         The second case used to invent a default and write it over the file, which\n\
         silently destroyed whatever it said — so a mistyped `id` took every\n\
         `[[clip]]` declaration in the sidecar with it.\n\n\
         ### Naming clips over a plain strip\n\n\
         An Aseprite document carries tags and those become clips. A PNG carries\n\
         nothing, so a `.meta` can name ranges over one:\n\n\
         ```toml\n\
         frames = 70\n\
         frame_ms = 120\n\n\
         [[clip]]\n\
         name = \"idle_ne\"\n\
         from = 0\n\
         to = 3\n\n\
         [[clip]]\n\
         name = \"attack_ne\"\n\
         from = 4\n\
         to = 9\n\
         looping = false\n\
         frame_ms = 60\n\
         ```\n\n\
         This is the sidecar doing what it already does: saying the things the file\n\
         itself does not. It could say a PNG is a strip of 70 frames and not that\n\
         frames 0 to 3 are an idle, and both are equally absent from the image — so\n\
         generated placeholder art, procedural sheets and anything a script assembles\n\
         could not reach `anim.play`.\n\n\
         Ranges are inclusive and absolute frame numbers, so an off-by-one is a\n\
         diagnostic naming the clip (`DIM0604`) rather than a silent shift. A range\n\
         past the end, a backwards range, a missing name and two clips sharing a name\n\
         are all refused. Declaring no clips keeps the old behaviour: one clip called\n\
         `default` over every frame.\n\n\
         Overlapping clips **warn** (`DIM0605`) rather than failing. Reusing frames is\n\
         a real technique and Aseprite tags may overlap too, so refusing would be\n\
         stricter than the tool this mirrors — but `0..3` then `3..7` when `4` was\n\
         meant is worth saying out loud.\n\n\
         ### Telling the host something\n\n\
         `event.emit(kind, payload)` appends to a list the runtime drains with\n\
         `Session::drain_events`. That is how a Steam achievement fires, how a volume\n\
         change reaches the mixer, and how anything else platform-facing gets out: the\n\
         sandbox has no `package`, no FFI and no `io`, so the simulation cannot call a\n\
         platform SDK and should not be able to.\n\n\
         **Never hashed, and structurally so** — there is no field on `SimState` for a\n\
         later change to start hashing, the way the log lines are kept out entirely. If\n\
         emitting consumed a random number or wrote hashed state, a build with Steam\n\
         disabled would diverge from one with it on, which is the same argument that\n\
         shaped the sound list.\n\n\
         **A rollback re-emits.** Events are not snapshotted, so restoring a snapshot\n\
         does not put drained ones back and re-running a tick emits again. The\n\
         alternative would let a restore resurrect events the host had already acted\n\
         on. A host that needs exactly-once deduplicates; Steam already does, and so\n\
         can a game.\n\n\
         It is one-way. The host does not talk back: a settings menu owns its values in\n\
         the profile and emits changes outward, so the game stays the source of truth\n\
         and the runtime follows.\n\n\
         Each event carries the tick it was emitted on, so a host draining after several\n\
         ticks can still tell them apart. The payload is the `Value` scripts already\n\
         store, so lists stay ordered and there is no second serialisation. `dim run`\n\
         reports them, so an achievement that fires in a windowed build and not in CI is\n\
         visible rather than mysterious.\n\n\
         ### Saves and the profile\n\n\
         Two kinds of persistence, and conflating them is the bug.\n\n\
         A **run** is simulation state. `dim state save` writes one and `dim state load`\n\
         reads it back, exactly: the resumed run continues identically, RNG streams\n\
         included, or it is a different run. The tree goes out as canonical `.dim` text\n\
         rather than a second serialisation, because I2 already guarantees that\n\
         round-trips, and a save that is text is a save somebody can read. A save from\n\
         a different engine version is **refused** (`DIM1002`) rather than warned about:\n\
         a log that replays wrong announces itself as a divergence, while a save that\n\
         restores wrong just keeps playing.\n\n\
         A **profile** is what accumulates across runs -- knowledge, awards, unlocks.\n\
         It is reached through `profile.get`, `profile.put` and `profile.clear`, and it\n\
         is **not in `SimState` at all**. Not a field the hasher skips: absent, the way\n\
         the log lines are, because kept-out-entirely is one fewer thing to get wrong.\n\
         Two players on the same seed have different profiles, so a hashed one would\n\
         make their replays diverge for a reason that has nothing to do with the game.\n\
         It is not snapshotted either, so a rollback does not take back an award.\n\n\
         **The hazard this cannot fix.** Keeping the profile out of the hash stops it\n\
         *being* hashed; it does not stop a script reading from it and writing what it\n\
         read into state. A line like `if profile.get(k) then self.spell = 1 end` makes\n\
         two players\' simulations differ, and hashing the profile would not help -- it\n\
         would turn a silent divergence into a loud one at the cost of making every\n\
         replay depend on who is playing. So the rule is one a game has to follow: **a\n\
         profile value may decide what is drawn, offered or unlocked, and may not decide\n\
         what the simulation does.** Choose a loadout from it at the menu, before the\n\
         run begins, and carry the choice in through `scene.request_load`, where it is\n\
         hashed like everything else.\n\n\
         ### Tiles\n\n\
         `tiles` reads and writes a `TileLayer`\'s grid while the game runs, which is\n\
         what a generated map needs: a roguelike builds its floor when you arrive from\n\
         the run\'s seed, and authoring floors as `.dim` files is the genre\'s negation.\n\n\
         **Writes are deferred to the end of the tick**, like `scene.spawn`, because a\n\
         script that changed the grid mid-tick would change it under every script that\n\
         had not run yet — and which terrain a monster saw would depend on where it fell\n\
         in the traversal. The useful consequence is that **reads need no snapshot**:\n\
         the grid does not change inside a tick at all, so a read during one is already\n\
         the grid as it stood when the tick began.\n\n\
         A cell nobody has painted reads as tile `0` rather than failing. A generator\n\
         checks the neighbours of an edge cell constantly, and an error for that would\n\
         mean bounds-checking every read. `tiles.bounds` reports where a layer has\n\
         storage, at chunk granularity, which is what a generator wants to iterate.\n\n\
         Tiles are part of the scene and the scene is hashed, so a painted tile moves\n\
         the state hash and a rollback rewinds the grid. A floor generated from a seed\n\
         therefore comes out identical on every machine, which is what makes a\n\
         generation bug arrive as a seed.\n\n\
         This does **not** go through the command bus, and that is deliberate rather\n\
         than an omission. The bus is the authoring path: a `SceneDoc` carries a TOML\n\
         document beside the model and a command keeps the two in step so a file can be\n\
         written back and undone. A running simulation has no document, and every tick\n\
         already moves nodes without a command in sight — `scene.spawn` does not use the\n\
         bus either. What *is* shared with the bus is the chunk handling, which lives in\n\
         `dimetric_scene::chunk` and has one implementation.\n\n\
         ### UI\n\n\
         `ui` reads what the pointer is doing to the interface, worked out inside the\n\
         tick — layout and hit testing run in a `UiUpdate` phase before scripts, so a\n\
         click on a menu is replayable like any other input. `ui.clicked(node)` is true\n\
         on the one tick a press and a release completed on that control; sliding off\n\
         before letting go cancels it.\n\n\
         **`ui.pointer()` is a canvas pixel, not a world position.** The canvas is the\n\
         fixed virtual resolution the project declares in `project.toml`, scaled to\n\
         whatever window the game gets — so the value is the same on every monitor,\n\
         which is what makes a recorded click land on the same button when it replays.\n\
         Getting from there to a world position means inverting the camera; see\n\
         `camera.to_world`.\n\n\
         `ui.captured()` is reported rather than enforced: the engine will not silently\n\
         swallow a click that landed on a control, because a script that never asked\n\
         would have no way to find out why its fire button stopped working over a menu.\n\n\
         Focus is tracked, not driven. `ui.focus_next(step)` walks the focusable\n\
         controls in tree order, and *which key* walks a menu is the game\'s decision —\n\
         binding it here would mean the engine deciding that pressing Down in a menu\n\
         can never also move the player.\n\n\
         ### Tweens and animation\n\n\
         Tweens and animation are simulation state, not presentation. They advance on\n\
         ticks, they are snapshotted, and they are in the state hash — a tween outside\n\
         the hash could not survive a rollback, and would be left mid-flight writing to\n\
         positions that had just been rewound. Easing runs in fixed point for the same\n\
         reason everything else does. The easings are `linear`, `ease_in`, `ease_out`\n\
         and `ease_in_out`; `pos`, `scale`, `rot` and any scalar, vector, angle or\n\
         colour property can be tweened.\n\n\
         Animation clips come from the importer with their frame durations already in\n\
         ticks. `on_anim_event(self, name)` fires when playback reaches a frame that\n\
         carries an event, which is how a hitbox opens on the swing frame rather than\n\
         on a timer someone has to keep in sync by hand.\n\n\
         ### Sound\n\n\
         `node:play()` on a `Sound` node asks for its clip; `node:stop()` stops what\n\
         that node started. The script says *when* and the node's properties say what,\n\
         on which bus, how loud and how far the pitch wanders — so an instance override\n\
         can change a sound and a designer can find it.\n\n\
         The simulation never plays anything. It appends to a list that is cleared at\n\
         the start of every tick and **is not hashed**, and whoever is listening reads\n\
         it. If a trigger consumed a random number or wrote hashed state, muting a game\n\
         would change how it plays and a run recorded with audio on would diverge from\n\
         one played with it off. `dim run` reports how many sounds a headless run asked\n\
         for.\n\n\
         ### Modules\n\n\
         `require(\"scripts/spellbook.lua\")` runs that script once and hands back\n\
         what it returned — the project-relative path a scene would write after\n\
         `script:`, one spelling rather than several to guess between. Every\n\
         script in a project is loaded before any of them runs, so requiring one\n\
         does not depend on where its name falls in the alphabet, and a cycle is\n\
         an error naming the loop.\n\n\
         What comes back is **read-only, all the way down**. A module's table is\n\
         not part of the state: it is not hashed, not snapshotted and not\n\
         rewound, so anything written into it would survive a rollback that\n\
         rewound everything around it — a divergence that surfaces hours later\n\
         in a replay rather than at the write. A module holds constants and pure\n\
         functions; state belongs in node variables, where the hash can see it.\n\
         The engine enforces the first part and not the second: a module\n\
         function that closes over a local and mutates it is out of reach of any\n\
         guard, and is the one way left to hide state from the hash.\n\n\
         Reloading a module re-runs every script, because a script that required\n\
         it is holding the table it returned and reloading one file would leave\n\
         that script reading the previous version's constants.\n\n\
         ### The rule that matters\n\n\
         Lua numbers are `f64`. Gameplay arithmetic done in raw Lua numbers and written\n\
         into simulation state is the easiest way to break replay. Use `vec2` and `fx`\n\
         values, which do their arithmetic in fixed point.\n\n\
         The sandbox has no `os`, `io`, `dofile`, `load` or `package`, and no\n\
         `math.random` — randomness comes from a seeded `rng` stream. `math.sin` and the\n\
         other transcendental functions are also absent, because platform maths libraries\n\
         do not agree with each other; use `fx.sin` and `fx.cos`, which read committed\n\
         lookup tables. `rawset` is absent too: it writes past a `__newindex`, which is\n\
         the guard holding a required module read-only.\n",
    );
    Ok(out)
}
